### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by fei1234** [JourneyYoung/iOSMixProject#1]
-spamCodeOut  这个方法执行，就会崩溃。
-handleXcassets  这个方法，控制台打印出来是 正在修改API。。。修改 Xcassets 中的图片名称完成,一共有0个图片文件，修改了0个

**Comment by JourneyYoung** [comment]
嗨，感谢你的邮件，这个脚本写的很匆忙，spamcodeOut执行崩溃的原因我还没有仔细查找，混淆图片的方法如下
if (needHandleXcassets) {
            @autoreleasepool {
//                handleXcassetsFiles(gSourceCodeDir);
                printf("正在修改API。。。");
                deleteAllSpamCode(gSourceCodeDir,@"sp_");
            }
请将deleteAllSpamCode代码注释掉，然后打开handleXcassetsFiles代码，deleteAllSpamCode是我测试删除垃圾代码方法时的临时入口~~

**Comment by JourneyYoung** [comment]
我已经更新了，我刚跑了没问题，里面可能有些测试代码，毕竟我一直在改东西，如果有没有跑的方法，建议你打个断点调试下，注释我都写了的。。

**Comment by JourneyYoung** [comment]
另外changeAPIname这个我新增的混淆方法的临时入口也在改图里，如有需要，自行注释或者打开注释。。

**Comment by fei1234** [comment]
好的  谢谢
