### ISSUE TITLE
程序更新

### ISSUE THREAD

**Issue by llbug13** [JourneyYoung/iOSMixProject#15]
我根据自己的包，重写了一道你的程序，并且都能成功的运行。你说5月修改了审核机制，能详细的说说修改了什么？

**Comment by jaccty** [comment]
能过审吗？楼主的程序还能用吗？

**Comment by JourneyYoung** [comment]
5月以后单纯修改类名工程名+方法名前缀不顶用，包吃2.1规则，还是得自己去摸摸苹果的脾气

**Comment by llbug13** [comment]
修改界面，改图片，改工程名，改方法，修改宏中的字符串。会后还是被打回来了，没用最新的sdk11.4和Facebook是开发者模式。下次提交应该会过。
