### ISSUE TITLE
想开源，又不想给伸手党

### ISSUE THREAD

**Issue by fangyuxi** [JourneyYoung/iOSMixProject#17]
思路很惊奇，想开源，又不想给伸手党。。。。
那你说怎么才不算伸手党呢？

**Comment by JourneyYoung** [comment]
谁说我想开源，我只是买不起私有库而已23333，黑灰产那么挣钱，我凭什么开源? 不知道是谁思路惊奇

**Comment by fangyuxi** [comment]
不开源就别来github里面说了哦，再说现在混淆代码也不是什么百分百的方式了。

**Comment by JourneyYoung** [comment]
啧，我也没说百分百，我开源这个脚本不过是一起学习，又不是送你们这些做马甲包的包过，不要曲解了开源精神
