### ISSUE TITLE
有点问题请教一下

### ISSUE THREAD

**Issue by zhujieshan** [JourneyYoung/iOSMixProject#2]
![2018-03-24 12 17 31](https://user-images.githubusercontent.com/23182986/37860293-5dfb15a2-2f5d-11e8-89de-0e78cb404491.png)

控制台返回:
删除注释和空行完成
正在生成垃圾代码
生成垃圾代码完成
Program ended with exit code: 0

但是我发现工程里面也没有删除注释和空行 和生成垃圾代码 不知道有什么步骤漏了 如果可以的话 可以在demo里面带一个混淆后的工程么?

**Comment by JourneyYoung** [comment]
在main函数里看下spamcodeOut方法是否执行，以及删除注释和空行的方法是否执行。在main函数中看。可能因为我写测试代码给注释掉了
