### ISSUE TITLE
修改API 代码里面怎么是删除代码 然后实现又是空的

### ISSUE THREAD

**Issue by YelCode** [JourneyYoung/iOSMixProject#26]
needModifyAPIName 调用deleteAllSpamCode
然后实现又是空的

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by JourneyYoung** [comment]
因为没写，改行做后台了~

**Comment by YelCode** [comment]
老哥 稳 要不要这么六？
做Java吗？
