### ISSUE TITLE
-spamCodeOut这个方法 代码老是数组越界怎么回事

### ISSUE THREAD

**Issue by jonsnowwinterfell** [JourneyYoung/iOSMixProject#8]
2018-04-26 11:10:06.847055+0800 ProjectMix[24420:438511] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 18446744073709551615 beyond bounds for empty array'
*** First throw call stack:

  崩在471行
  NSNumber *number = arrayOfLocation[arrayOfLocation.count-1];

**Comment by JourneyYoung** [comment]
我记得代码里的添加逻辑是找到.h\.m文件找到@end关键字然后去前面插入垃圾代码，可能与你实际工程构造冲突，你可以查看crash时被插入的代码内容，修改插入逻辑以适配你的项目~

**Comment by leoxpx** [comment]
NSString *s = @"@end";
            NSArray *endArray = [mfileContent componentsSeparatedByString:s];
            
            if (endArray.count < 2) {
                return;
            }
            
            NSMutableArray *arrayOfLocation=[NSMutableArray new];
            int d=0;
            for (int i=0; i<endArray.count-1; i++) {
                
                NSString *string=endArray[i];
                NSNumber *number=[NSNumber numberWithInt:d+=string.length];
                
                d+=s.length;
                [arrayOfLocation addObject:number];
                
            }

**Comment by turboxing** [comment]
加了判断之后 应该不会越界了吧，那垃圾代码顺利添加成功了吗？ @leoxpx

**Comment by turboxing** [comment]
为什么有些类里面并没有插入垃圾代码

**Comment by leoxpx** [comment]
@turboxing 添加成功了, 但是有些 @end结尾的类 后面还有#endif语句, 依然有问题

**Comment by turboxing** [comment]
工程名修改管用吗 试过没 我这边执行完修改工程名 无效

发自我的 iPhone

**Comment by cc2436** [comment]
大佬 插入辣鸡代码时报错 看文件好像是打开了Pods里边的文件 对其进行代码注入了 怎么回事啊
