### ISSUE TITLE
Xib类文件的前缀修改好像不起作用？

### ISSUE THREAD

**Issue by xabodog** [JourneyYoung/iOSMixProject#9]

**Comment by xabodog** [comment]
还有category貌似也不管用，另外-modifyAPIName具体是改变接口名字，具体原理是什么，我用了后不知道代码哪里修改了

**Comment by JourneyYoung** [comment]
莫非你的xib是放在资源文件夹里的？不和.h.m文件在一起是不识别的，具体你看看脚本
